# class DataIngestionConfig:
#     pass
# above code syntax can also shorthand as follows
class DataIngestionConfig:...
class DataValidationConfig:...
class DataTransformationConfig:...
class ModelTrainerConfig:...
class ModelEvaluationConfig:...
class ModelPusherConfig:...